title: "Harang's Robotics Log"
description: "Control · Dynamics · Robotics · Vision"
lang: "ko"
timezone: "Asia/Seoul"

theme: minima

# 메뉴(상단 네비게이션)
header_pages:
  - about.md
  - projects.md


plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/jiharangrang" }
