title: "Harang Robotics Log"
description: "Control · Dynamics · Robotics · Vision"
lang: "en"
timezone: "Asia/Seoul"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag


minimal_mistakes_skin: "default"


nav:
  - title: "About"
    url: /about/
  - title: "Posts"
    url: /posts/
  - title: "Projects"
    url: /projects/


author:
  name: "Harang Ji"
  bio: "Mechanical Engineering student."
  location: "Seoul, Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jiharangrang"
